### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [gtaifu/qasm_highlighting#3]
Hi;
maybe possible to make QASM highlighting (ie lexer) for CudaText too?

**Comment by gtaifu** [comment]
The QuMIS language is defined by ourselves. The QASM is based on our own syntax. Till now, only people from our groups working on quantum computing are using it. They mostly work use Sublime and vim.
If there are more people who need to highlight the QuMIS and QASM in CudaText, I can spend some time making it happen.
